const json=(v,s=200,extra={})=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...extra}});
const enc=new TextEncoder();
function b64(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function un64(s){return Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4)),x=>x.charCodeAt(0))}
async function key(secret){return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',enc.encode(secret)),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function seal(obj,secret){const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(secret),enc.encode(JSON.stringify(obj)));return b64(iv)+'.'+b64(new Uint8Array(cipher))}
async function unseal(s,secret){try{const [i,c]=s.split('.');return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(i)},await key(secret),un64(c))))}catch{return null}}
function cookies(req){return Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>x.trim().split(/=(.*)/s).slice(0,2)).filter(x=>x.length===2))}
function cookie(name,value,maxAge){return `${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
function redirect(to,cs=[]){const h=new Headers({location:to,'cache-control':'no-store'});cs.forEach(x=>h.append('set-cookie',x));return new Response(null,{status:302,headers:h})}
function originAllowed(req,env){const origin=req.headers.get('origin');return !origin||origin===env.PAGES_ORIGIN}
function cors(req,env,response){const h=new Headers(response.headers);if(req.headers.get('origin')===env.PAGES_ORIGIN){h.set('access-control-allow-origin',env.PAGES_ORIGIN);h.set('access-control-allow-credentials','true');h.set('vary','Origin')}return new Response(response.body,{status:response.status,headers:h})}
function validate(list){if(!Array.isArray(list)||list.length>100)throw Error('商品必须为数组，最多100件');const ids=new Set();const hosts={amazon:['amazon.de'],mediamarkt:['mediamarkt.de'],otto:['otto.de']};for(const p of list){if(!p||typeof p.id!=='string'||! /^[a-zA-Z0-9_-]{1,90}$/.test(p.id)||ids.has(p.id))throw Error('商品ID无效或重复');ids.add(p.id);if(typeof p.name!=='string'||!p.name.trim()||p.name.length>160)throw Error('商品名称无效');if(p.enabled!==undefined&&typeof p.enabled!=='boolean')throw Error('enabled必须为布尔值');if(p.target_price!==null&&p.target_price!==undefined&&(!Number.isFinite(p.target_price)||p.target_price<0))throw Error('目标价格无效');if(!p.links||typeof p.links!=='object'||Array.isArray(p.links))throw Error('缺少链接');if(Object.keys(p.links).some(s=>!hosts[s]))throw Error('不支持的平台');let count=0;for(const [shop,raw] of Object.entries(p.links)){if(!raw)continue;if(typeof raw!=='string'||raw.length>2000)throw Error('链接无效');let u;try{u=new URL(raw)}catch{throw Error('链接格式无效')}if(u.protocol!=='https:'||!hosts[shop].some(h=>u.hostname===h||u.hostname.endsWith('.'+h)))throw Error(shop+' 链接域名错误');count++}if(!count)throw Error('每件商品至少一个链接')}}
async function gh(env,method,body,sha){const url=`https://api.github.com/repos/${encodeURIComponent(env.GITHUB_OWNER)}/${encodeURIComponent(env.GITHUB_REPO)}/contents/products.json`;const headers={'authorization':`Bearer ${env.GITHUB_REPO_TOKEN}`,'accept':'application/vnd.github+json','x-github-api-version':'2022-11-28','user-agent':'price-tracker-worker'};if(method==='PUT')headers['content-type']='application/json';const r=await fetch(url,{method,headers,body:method==='PUT'?JSON.stringify({message:'Update monitored products via admin',content:b64(enc.encode(JSON.stringify(body,null,2)+'\n')),sha}):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(Error(data.message||'GitHub API error'),{status:r.status});return data}
export default {async fetch(req,env){const u=new URL(req.url),path=u.pathname;try{
if(!env.PAGES_ORIGIN||!env.SESSION_SECRET||!env.GITHUB_CLIENT_ID||!env.GITHUB_CLIENT_SECRET||!env.GITHUB_REPO_TOKEN||!env.GITHUB_OWNER||!env.GITHUB_REPO||!env.ALLOWED_GITHUB_LOGIN)return json({error:'Worker environment incomplete'},503);
if(req.method==='OPTIONS'){if(!originAllowed(req,env))return json({error:'Origin rejected'},403);return cors(req,env,new Response(null,{status:204,headers:{'access-control-allow-methods':'GET,PUT,OPTIONS','access-control-allow-headers':'content-type,x-csrf-token','access-control-max-age':'600'}}))}
if(path==='/admin.html'||path==='/worker-config.js')return env.ASSETS.fetch(req);
if(path==='/auth/login'){const state=b64(crypto.getRandomValues(new Uint8Array(24)));const callback=new URL('/auth/callback',u.origin).href;const auth=new URL('https://github.com/login/oauth/authorize');auth.searchParams.set('client_id',env.GITHUB_CLIENT_ID);auth.searchParams.set('redirect_uri',callback);auth.searchParams.set('scope','read:user');auth.searchParams.set('state',state);return redirect(auth.href,[cookie('oauth_state',state,600)])}
if(path==='/auth/callback'){const c=cookies(req);if(!u.searchParams.get('state')||u.searchParams.get('state')!==c.oauth_state)return json({error:'OAuth state mismatch'},403);const r=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{accept:'application/json','content-type':'application/json','user-agent':'price-tracker-worker'},body:JSON.stringify({client_id:env.GITHUB_CLIENT_ID,client_secret:env.GITHUB_CLIENT_SECRET,code:u.searchParams.get('code'),redirect_uri:new URL('/auth/callback',u.origin).href})});const token=(await r.json()).access_token;if(!token)return json({error:'GitHub OAuth failed'},401);const ur=await fetch('https://api.github.com/user',{headers:{authorization:`Bearer ${token}`,'user-agent':'price-tracker-worker','accept':'application/vnd.github+json'}});const profile=await ur.json();if(!ur.ok||String(profile.login||'').toLowerCase()!==env.ALLOWED_GITHUB_LOGIN.toLowerCase())return json({error:'GitHub user not authorized'},403);const csrf=b64(crypto.getRandomValues(new Uint8Array(20)));const session=await seal({login:profile.login,csrf,exp:Date.now()+7*86400000},env.SESSION_SECRET);return redirect(new URL('/admin.html',u.origin).href,[cookie('oauth_state','',0),cookie('pt_session',session,604800)])}
if(path==='/auth/logout'){return redirect(new URL('/admin.html',u.origin).href,[cookie('pt_session','',0)])}
if(!originAllowed(req,env))return json({error:'Origin rejected'},403);
const sess=await unseal(cookies(req).pt_session||'',env.SESSION_SECRET);if(!sess||sess.exp<Date.now()||sess.login.toLowerCase()!==env.ALLOWED_GITHUB_LOGIN.toLowerCase())return cors(req,env,json({error:'not_authenticated'},401));
if(path==='/api/me'&&req.method==='GET')return cors(req,env,json({login:sess.login,csrf:sess.csrf}));
if(path==='/api/products'&&req.method==='GET'){const data=await gh(env,'GET');return cors(req,env,json({products:JSON.parse(new TextDecoder().decode(un64(data.content.replace(/\s/g,'').replace(/\+/g,'-').replace(/\//g,'_')))),sha:data.sha}))}
if(path==='/api/products'&&req.method==='PUT'){if(req.headers.get('x-csrf-token')!==sess.csrf)return cors(req,env,json({error:'CSRF token mismatch'},403));const raw=await req.text();if(raw.length>350000)return cors(req,env,json({error:'Payload too large'},413));const data=JSON.parse(raw);validate(data.products);if(!/^[a-f0-9]{40}$/.test(data.sha||''))throw Error('Missing version SHA');await gh(env,'PUT',data.products,data.sha);return cors(req,env,json({ok:true}))}
return cors(req,env,json({error:'Not found'},404));
}catch(e){return cors(req,env,json({error:e.message||'Server error'},e.status===409?409:e.status===422?409:e.status===401?401:400))}}};
